### ISSUE TITLE
[ALL] Understand how persistent of pocketbase instance on Hop.io works

### ISSUE THREAD

**Issue by maxoja** [maxoja/jampify-core#13]
Understand how this work, is it due to Hop.io specific mechanics or it's a Docker thing. Is there anything I need to do extra to  make sure that restart won't end up with all existing data flushed out

**Comment by ktunprasert** [comment]
Auto backup is a feature in Pocketbase now - point to any s3 compatible storage for free win in the settings

**Comment by maxoja** [comment]
@ktunprasert I think my knowledge gap is about how Hop.io maintains the created drive. Would it get destroyed on every deployment and would I have direct access to the drive to do something and whether I can increase the drive capacity by only interactions with Hop.io

**Comment by ktunprasert** [comment]
@maxoja If it's anything like Fly.io then 
1. You can always ssh into the instance and manual backup
2. You can view the persistent storage directly, usage stats and the like via web ui
3. You have to configure the mount tied to where you want the data to "persist" (see image)

https://docs.hop.io/ignite/volumes
After giving this a read, it seems to be working in the same way, configure the "mount path" to your `/pb_data` and it should persist, ez pz lemon sqzy

![image](https://github.com/maxoja/jampify-core/assets/35368006/d8c186ed-0cc4-4a87-96a4-e74131a8d4f7)

**Comment by maxoja** [comment]
Sorry, I was on a week break from this project but now I'm back @ktunprasert

Thanks a lot bro, this is exactly what I need to read about. I'm digging and will get back summarising this then close this issue

**Comment by maxoja** [comment]
It seems there can only be 1 volume mounted to the existing container (even after payment method added) so I tried creating new ignite container using MongoDB template and there's this configuration similar to what was mentioned which is optional be default
![image](https://github.com/maxoja/jampify-core/assets/11785512/3d0c9207-e8ce-4ebb-84aa-3caafb8315a8)

I don't think we can SSH into the box and it also seems the mounting configuration lives in their backend configurable only through UI/CLI and not yml config at least it's not used to store initial config but potentially is for overriding

I still haven't found a way to back up the storage without Pocketbase. Tho there is a nice UI for mounted volume exploration 
![image](https://github.com/maxoja/jampify-core/assets/11785512/aa20600f-953d-45cb-9b22-5953e972f311)

There're more configuration through CLI than the UI, for example scaling strategy
https://docs.hop.io/ignite/overview#containers

**Comment by maxoja** [comment]
In conclusion, it's most convenient to just backup through PB for now.
For infrequent manual backup we can download each item on the drive through Volume Explorer UI but that's not ideal
![image](https://github.com/maxoja/jampify-core/assets/11785512/c2966131-848b-4f04-ae16-0d46926990b1)

**Comment by maxoja** [comment]
Oh wait, seems we can setup port fwding for SSH but I'll stop digging now as it's not blocking me. I found this conversation on Discord. Looks we need extra setup
https://docs.hop.io/ignite/port-forwarding
![image](https://github.com/maxoja/jampify-core/assets/11785512/78b73505-3c92-4d92-8a64-0e9822535bb2)

**Comment by maxoja** [comment]
I don't think it's out of the box as claimed on the conversation 
![image](https://github.com/maxoja/jampify-core/assets/11785512/9cf9d669-c75c-4aad-8554-36d0207637b5)
